### PR TITLE
Fix "Attempted relative import in non-package" exception.

### PR DESCRIPTION
**Pull request by alecthomas**

### CODE REVIEW

**Comment by alecthomas** [comment]
This should fix #9. I don't have Sublime 3 though, so I don't know if it works there or not.

**Comment by vojtajina** [comment]
@alecthomas please make sure it works with ST3, I don't think this does.

**Comment by alecthomas** [comment]
I don't have ST3, but it definitely doesn't work in ST2 :\

**Comment by vojtajina** [comment]
Ok, let's create a branch for ST2. I don't think there's a way to define this import to work with both python 2 and 3.

**Comment by vojtajina** [comment]
@alecthomas can you figure out what's the best way to do it ? https://sublime.wbond.net/docs/developers
I can give you push permissions to this repo.

**Comment by alecthomas** [comment]
I think it can be fixed for both versions by moving the files into a package (eg. openrelated), then having a stub .py file in the root import the package. Once imported as a package, the relative imports should work fine.

**Comment by vojtajina** [comment]
@alecthomas if you feel like doing it, please re-open this PR. I'm closing it as I think it's more important to keep this plugin working with ST3.

**Pull request closed without merging**
